# Generated by Django 3.1.7 on 2021-05-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookproduct',
            options={'ordering': ('product_name', 'price'), 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelManagers(
            name='bookcategory',
            managers=[
            ],
        ),
    ]
