# Generated by Django 3.1.7 on 2021-05-14 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210515_0115'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookproduct',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='bookproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='main.bookcategory'),
        ),
    ]
